[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
homechance_raffle = "BAkZeFEefRiGYj8des7zXoTpWwNNcfj6NB5694PCTHKo"

[programs.devnet]
homechance_raffle = "BAkZeFEefRiGYj8des7zXoTpWwNNcfj6NB5694PCTHKo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
